### ISSUE TITLE
The parameter is incorrect.  'name': A group name must be 40 characters or less.

### ISSUE THREAD

**Issue by aherrick** [CrossGeeks/FileUploaderPlugin#11]
Trying to call `UploadFileAsync`.

Receiving the following error on all platforms:

`The parameter is incorrect. 'name': A group name must be 40 characters or less.`

My code looks like the following:

```
    var items = new List<FilePathItem>();
    items.Add(new FilePathItem("parm1", parm1data.ToString()));
    items.Add(new FilePathItem("parm2", "parm2data"));

    var result = await CrossFileUploader.Current.UploadFileAsync("url", items.ToArray(), "");
```

Am I not calling/initializing the plugin correctly?

**Comment by rdelrosario** [comment]
I think the third parameter shouldn't be empty.

**Comment by aherrick** [comment]
Hi @rdelrosario I've updated the third parameter to some random text and I receive the following:

`The parameter is incorrect.`

It isn't clear what the third parameter should be...

**Comment by rdelrosario** [comment]
Here is an example:

```
CrossFileUploader.Current.UploadFileAsync("<URL HERE>", new FilePathItem[]{
    new FilePathItem("file",path1),
	new FilePathItem("file",path2),
	new FilePathItem("file",path3)
 },"Upload Tag 1");
```

**Comment by rdelrosario** [comment]
I think you have "param1", "param2". Do you have this set on the server like that? generally if you don't set it name of the parameter is "file"

**Comment by aherrick** [comment]
No, that was just an example. I realize the file names need to match up with the Server.

The call is failing before the server request even goes off.

I guess I'm just confused why the parameter "Upload Tag 1" is needed?

**Comment by rdelrosario** [comment]
If you upload make several upload calls that's the way to identify which of the calls/batch was uploaded since it triggers FileUploadCompleted which has the tag information on the arguments.

For example:
```cs
CrossFileUploader.Current.UploadFileAsync("<URL HERE>", new FilePathItem[]{
    new FilePathItem("file",path1),
	new FilePathItem("file",path2),
	new FilePathItem("file",path3)
 },"Batch 1");
CrossFileUploader.Current.UploadFileAsync("<URL HERE>", new FilePathItem[]{
    new FilePathItem("file",path1),
	new FilePathItem("file",path2),
	new FilePathItem("file",path3)
 },"Batch 2");
CrossFileUploader.Current.UploadFileAsync("<URL HERE>", new FilePathItem[]{
    new FilePathItem("file",path1),
	new FilePathItem("file",path2),
	new FilePathItem("file",path3)
 },"Batch 3");
```
