### ISSUE TITLE
How do i pick/select  multiple images from gallery at a time?( Xamarin Forms)

### ISSUE THREAD

**Issue by SatyaRamprasad** [CrossGeeks/FileUploaderPlugin#3]
Uploading multiple files at once

 CrossFileUploader.Current.UploadFileAsync("<URL HERE>", new FilePathItem[]{
    new FilePathItem("file",path1),
	new FilePathItem("file",path2),
	new FilePathItem("file",path3)
 },"Upload Tag 1");

It is for Upload images to server and how do i pick/select images from gallery?(Multi select Images)

**Comment by rdelrosario** [comment]
This plugin is just for uploading images. There are other plugins to pick/select images like: 

https://github.com/jamesmontemagno/MediaPlugin

**Comment by rdelrosario** [comment]
Also checkout this post: https://xamgirl.com/select-multiple-images-from-gallery-in-xamarin-forms/
