### ISSUE TITLE
Pass Bearer Token to UploadFileAsync

### ISSUE THREAD

**Issue by alirazamsp** [CrossGeeks/FileUploaderPlugin#33]
For HttpClient, we can pass bearer token to our endpoint like this: 
`httpClient.DefaultRequestHeaders.Authorization =
    new AuthenticationHeaderValue("Bearer", "Your Oauth token");`

For this plugin, we can pass headers and parameters. I need a way to pass bearer token to upload files. I tried it in dictionary as a header and parameter both but it does not work and gives 401 unauthorised. I can pass it to the HttpClient with 200 OK status code.

**Comment by TaiPhamDuc** [comment]
I know it's late, but I still reply here because I want to share with people who don't know how to do it.
`var response = await CrossFileUploader.Current.UploadFileAsync(Constants.UploadFileEndpoint, 
                new FilePathItem("Content",YourFile), new Dictionary<string, string>()
                {
                    {"Authorization", $"Bearer {Token}"},
                }
            );`
