### ISSUE TITLE
alue cannot be null. Parameter name: url   at Foundation.NSMutableUrlRequest

### ISSUE THREAD

**Issue by lumisoftusa** [CrossGeeks/FileUploaderPlugin#4]
![error](https://user-images.githubusercontent.com/5659771/34355865-5e3e83e8-ea5a-11e7-827a-86e76eec5ea1.png)
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by rdelrosario** [comment]
What platform are you testing on?

**Comment by rdelrosario** [comment]
Physical device?

**Comment by rdelrosario** [comment]
The issue seems the url is null you might be passing a wrong url.
