### ISSUE TITLE
FileUploadProgress doesn't return tag

### ISSUE THREAD

**Issue by neurospeech** [CrossGeeks/FileUploaderPlugin#7]
There is no way to identify progress of which file is being uploaded when multiple files are uploaded. Just like `FileUploadResponse`, `FileUploadProgress` should have field for `tag`.

**Comment by rdelrosario** [comment]
Try this version just published it with that change:

https://www.nuget.org/packages/Plugin.FileUploader/1.3.6-beta

**Comment by johnfurog** [comment]
Getting this error upon trying 1.3.6-beta


System.MissingMethodException: Method 'Plugin.FileUploader.Abstractions.FileUploadProgress.get_Tag' not found.

**Comment by rdelrosario** [comment]
Weird, are you sure you updated the NuGet on all your projects of the solution? Seems is referencing the old abstractions dll. Try cleaning the project and rebuilding.

**Comment by rdelrosario** [comment]
On Android or iOS?

**Comment by johnfurog** [comment]
on android ..

**Comment by johnfurog** [comment]
here is the code snippet
![image](https://user-images.githubusercontent.com/33830386/35134122-60588544-fd0f-11e7-8c65-e52679b731c8.png)

**Comment by rdelrosario** [comment]
Where are you subscribing to the FileUploadCompleted event?

**Comment by rdelrosario** [comment]
Will close this issue now, latest version return tag in FileUploadProgress. If you have any other issue please open a new one.
